apiVersion: v1
kind: Pod
metadata:
  name: {{ include "kind.fullname" . }}
  labels:
  {{- include "kind.selectorLabels" . | nindent 4 }}
  {{- include "kind.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  serviceAccountName: {{ include "kind.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  containers:
    - name: {{ .Chart.Name }}
      stdin: true
      tty: true
      args:
        - /bin/bash
      env:
        - name: API_SERVER_ADDRESS
          value: 0.0.0.0
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: api-server
          containerPort: 30001
          protocol: TCP
      readinessProbe:
        failureThreshold: 15
        httpGet:
          path: /healthz
          port: api-server
          scheme: HTTPS
        initialDelaySeconds: 120
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
