apiVersion: v1
kind: Service
metadata:
  name: {{ include "kind.fullname" . }}
  labels:
    {{- include "kind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-server
      protocol: TCP
      name: api-server
  selector:
    {{- include "kind.selectorLabels" . | nindent 4 }}
